<a href="https://colab.research.google.com/github/Carlise98/03MIAR---Algoritmos-de-Optimizacion/blob/main/02_AO_03MIAR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="#002856"><h1 align="left">Algoritmos de optimización</h1></font>
<font color="#002856"><h2 align="left">VC-2 Diseño de algoritmos</h2></font>

#### Profesor: Juan Francisco Vallalta Rueda
---

# Medir el tiempo de ejecución

Medir el tiempo de ejecución de un programa es una tarea muy importante, ya que programar no sólo consiste en crear código que funcione, sino código que pueda ser ejecutado en un tiempo razonable.

La librería **time** nos permite medir el tiempo de ejecución en Python, utilizando el método  `time()`.

In [ ]:
# Medida del tiempo de ejecucion con time
import time
inicio = time.time()

# Código a medir
time.sleep(10)
# -------------

fin = time.time()
print(fin-inicio) # 1.0005340576171875

10.002641201019287


# Generación de números enteros aleatorios

In [ ]:
# Mödulo random
import random

# Inicialización del rango de números a generar
inicio= 0
fin = 1000
cantidad = 100

# Lista de números aleatorios
numeros_aleatorios = [random.randint(inicio,fin) for i in range(cantidad)]
print(numeros_aleatorios)

[695, 385, 928, 730, 82, 906, 416, 429, 707, 59, 556, 643, 489, 851, 385, 940, 465, 515, 942, 745, 219, 305, 8, 943, 218, 371, 483, 174, 136, 257, 482, 94, 385, 201, 530, 522, 460, 204, 882, 754, 24, 341, 576, 946, 97, 758, 491, 270, 746, 12, 652, 158, 483, 623, 710, 665, 856, 935, 963, 342, 247, 890, 673, 143, 54, 905, 868, 522, 1, 248, 690, 720, 363, 878, 567, 586, 593, 901, 574, 835, 853, 915, 188, 937, 489, 182, 228, 948, 247, 291, 223, 602, 741, 761, 199, 691, 72, 718, 965, 583]


# Ejercicios

## Implementa  una solución para el problema del cambio de moneda en un sistema monetario con las siguientes monedas: {1, 2, 5, 10, 20 , 50}

In [5]:
# Problema de cambio de monedas

def cambio(valor):
  monedas = [50, 20, 10, 5, 2, 1]

  for moneda in monedas:
    if moneda <= valor:
      print(f'Monedas de {moneda} = {int(valor/moneda)}')
      valor = valor - int(valor/moneda)*moneda



cambio(7)


Monedas de 5 = 1
Monedas de 2 = 1


# Reto VC-2

## Opción 1: Implementa una solución al problema de las 8 reinas en un tablero 8x8

In [53]:
import numpy as np
global N
N = 4


tablero = np.zeros([4,4])
print(tablero)
# Ocho reinas
# Escribe aquí tu código
def comprobar(tablero,col,fila):
  for i in range(4):
    if i != fila and tablero[col][i] == 1:
      return False
    if i != col and tablero[i][fila] == 1:
      return False

  print('Inserta')
  return True


def isSafe(board, row, col,numero):

    # Check this row on left side
    for i in range(col):
        if board[row][i] == 1:
            return False

    # Check upper diagonal on left side
    for i, j in zip(range(row, -1, -1),
                    range(col, -1, -1)):
        if board[i][j] == 1:
            return False

    # Check lower diagonal on left side
    for i, j in zip(range(row, numero, 1),
                    range(col, -1, -1)):
        if board[i][j] == 1:
            return False

    return True



def reina(tablero, numero, col):

  #Caso base
  if col >= numero:
    return True


  for i in range(numero):

    if isSafe(tablero,i,col,numero):

      tablero[i][col] = 1

      if reina(tablero, numero, col + 1) == True:
        return True

      tablero[i][col] = 0

  return False

# def solveNQUtil(board, col):

#     # Base case: If all queens are placed
#     # then return true
#     if col >= N:
#         return True

#     # Consider this column and try placing
#     # this queen in all rows one by one
#     for i in range(N):

#         if isSafe(board, i, col):

#             # Place this queen in board[i][col]
#             board[i][col] = 1

#             # Recur to place rest of the queens
#             if solveNQUtil(board, col + 1) == True:
#                 return True

#             # If placing queen in board[i][col
#             # doesn't lead to a solution, then
#             # queen from board[i][col]
#             board[i][col] = 0

#     # If the queen can not be placed in any row in
#     # this column col then return false
#     return False


def printSolution(board,numero):
    for i in range(numero):
        for j in range(numero):
            if board[i][j] == 1:
                print("Q",end=" ")
            else:
                print(".",end=" ")
        print()


numero = 8

# tablero = np.zeros([numero,numero])
board = [[0 for _ in range(numero)] for _ in range(numero)]

# solveNQUtil(tablero,0)
reina(board, numero, 0)

printSolution(board,numero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Q . . . . . . . 
. . . . . . Q . 
. . . . Q . . . 
. . . . . . . Q 
. Q . . . . . . 
. . . Q . . . . 
. . . . . Q . . 
. . Q . . . . . 


## Opción 2: Implementa una solución del problema de las Torres de Hanoi para un número arbitrario n de fichas

In [18]:
# Torres de Hanoy
# Escribe aquí tu código


